### ISSUE TITLE
Bug: apparent collision misses with convex polyhedra.

### ISSUE THREAD

**Issue by paulmartel** [w0rm/elm-physics#12]
These are suspected to be caused my inconsistent handling of opposite edge vectors which are supposed to have equivalent effects. Both convex/convex and (prototype) sphere/convex collisions seem to have similar issues.

**Comment by w0rm** [comment]
It's a tricky one. I have a rough idea how to tackle this. If we use fuzz tests to setup a scene with two randomly rotated bodies, one having zero mass, so it's static, and another falling down. We can then simulate the scene until we get collision points, and then measure the speed vector. My understanding is that when the overlap is too large, there is a weird bouncing effect.

**Comment by w0rm** [comment]
Apparently, we didn't fix all the issues with the Sphere & Box collision.

The following demo test case reproduces the issue:

```elm
module SphereBoxCollisionBug exposing (main)

import Common.Demo as Demo exposing (Demo, DemoProgram)
import Math.Vector3 as Vec3 exposing (Vec3, vec3)
import Physics
import Common.Bodies as Bodies exposing (DemoBody(..))

main : DemoProgram
main =
    Demo.demo
        |> Demo.addBodies
            [ Bodies.getBody DemoSphere
                (Physics.offsetBy (vec3 -0.7 -0.7 10))
            , Bodies.getBody DemoBox
                (Physics.setMass 0)
            ]
        |> Demo.run
```

When using the Elm Debugger and Wireframe visualisation, it is possible to see that there are two collision points, and a sphere jumps without any reason:

![physics](https://user-images.githubusercontent.com/43472/43105273-9d07307e-8ed4-11e8-8dc7-f9f28e49e243.gif)

**Comment by w0rm** [comment]
Apparently it produces the wrong contact equation, where vectors `ri` and `rj` don't point to the same contact. One of them is correct, but another rather points to the surface on the sphere.

**Comment by w0rm** [comment]
I think a good approach would be to visualize all the components of the contact equation

**Comment by w0rm** [comment]
@paulmartel I think I understand the collision bug between a convex & a sphere.

We first try to collide with vertices, then with edges and then finally with faces. We also prematurely exit if one of the steps produces a contact. The problem is though, that in some cases the face might be closer to the sphere than a vertex. Because we ignore this and keep the contact point with the vertex, the sphere rotates over the vertex and dives inside the convex. So when the sphere is already too deep inside the box and the contact with the vertex is lost, the repulsion kicks in.
